### ISSUE TITLE
error 'styled-components' required for `@rebass/grid/emotion`

### ISSUE THREAD

**Issue by sylvainbaronnet** [rebassjs/grid#167] opened 2018-12-25 14:46 UTC
Hi,

Looks like `styled-component` is required when using `@rebass/grid/emotion`, is it normal ?

`Error: Can't resolve 'styled-components' in '/Users/admin/Documents/git/tms/node_modules/@rebass/grid/emotion/dist'`

**Comment by jxnblk** [comment] 2018-12-31 18:20
The emotion version does not depend on styled-components. It looks like somewhere in your app the styled-components version *might* be getting imported. `@rebass/grid/emotion/dist` shouldn't exist, but `@rebass/grid/dist/emotion` should be the emotion version – can you provide more details, like the version of `@rebass/grid` you have installed?

**Comment by abhisheksoni27** [comment] 2019-01-07 11:47
I am having the same issue. I have installed: `"@rebass/grid": "^6.0.0-7"`

And I am not using `emotion`.

**Comment by igneel64** [comment] 2019-01-15 10:07
Been facing the same issue. @jxnblk  :/

**Comment by davidfurlong** [comment] 2019-01-30 13:49
Looks like styled-components should be listen as a peer dependency?
`
Module not found: Error: Can't resolve 'styled-components' in '/node_modules/@rebass/grid/dist'`

**Comment by jxnblk** [comment] 2019-01-31 15:56
@davidfurlong #158

**Comment by horyd** [comment] 2019-02-22 00:49
I'm getting this error as well, exactly as it appears for @davidfurlong. I'm trying to load a custom version of the `styled-components` repo

**Comment by pokonski** [comment] 2019-02-24 10:33
@jxnblk should this be fixed now? Still getting the error on `6.0.0-7`. Just by simply importing how the README says:  `import { Flex, Box } from '@rebass/grid'`

**Comment by jxnblk** [comment] 2019-02-24 17:37
To clarify: `@rebass/grid` is the styled-components version and `@rebass/grid/emotion` is the emotion version – you should only import either one or the other

Since I haven't seen updates from @sylvainbaronnet for a reproduction, I'm closing this issue out

**Closed by jxnblk** 2019-02-24 17:37 UTC

**Comment by sprazzeus** [comment] 2019-04-19 17:28
Same issue. Installed `"@rebass/grid": "^6.0.0"` in a create-react-app project, that doesn't use `styled-components` or `emotion`.

When doing `import { Flex, Box } from '@rebass/grid'` I get this error:
```./node_modules/@rebass/grid/dist/index.js
Module not found: Can't resolve 'styled-components' in '.../node_modules/@rebass/grid/dist'
```

And if I change it to `import { Flex, Box } from "@rebass/grid/emotion";` I get this error:
```./node_modules/@rebass/grid/dist/emotion/index.js
Module not found: Can't resolve '@emotion/styled' in '/Users/sprazzeus/Code/helix/node_modules/@rebass/grid/dist/emotion'
```

It works if I install `styled-components`.

**Comment by Pallandor** [comment] 2019-04-25 12:25
> Same issue. Installed `"@rebass/grid": "^6.0.0"` in a create-react-app project, that doesn't use `styled-components` or `emotion`.
> 
> When doing `import { Flex, Box } from '@rebass/grid'` I get this error:
> 
> ```js
> Module not found: Can't resolve 'styled-components' in '.../node_modules/@rebass/grid/dist'
> ```
> 
> And if I change it to `import { Flex, Box } from "@rebass/grid/emotion";` I get this error:
> 
> ```js
> Module not found: Can't resolve '@emotion/styled' in '/Users/sprazzeus/Code/helix/node_modules/@rebass/grid/dist/emotion'
> ```
> 
> It works if I install `styled-components`.

It's because, depending on the `@rebass/grid` variant you use, there is an (unmarked) peer dependency on either `styled-components` or `@emotion/styled` (Core emotion doesn't ship with the styled API flavour that this module relies on). 

If you intend to use the emotion variant, you need to do both of the following:
1. Install emotion core and styled (e.g. **`npm i --save @emotion/core @emotion/styled`**)
2. Import from `@rebass/grid/emotion` (e.g. **`import { Flex, Box } from "@rebass/grid/emotion"`**)

You shouldn't need to install styled-components alongside emotion then.
